name: Drill CI
on: [push, pull_request]

jobs:
  call:
    uses: ./.github/workflows/drill-build.yml
    with:
      image: demo
      push: ${{ github.event_name == 'push' }} # true только при push
    secrets:
      registry_token: ${{ secrets.NO_SUCH }}

  show:
    needs: call
    runs-on: ubuntu-latest
    steps:
      - run: echo "digest is ${{ needs.call.outputs.digest }}"
